name: NMUI SaaS Deployment to SaaS Prod

on:
  push:
    branches: [saas-prod]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to saas-prod"
        uses: actions/checkout@v4
        with:
          ref: saas-prod

      - name: Set release tag
        run: |
          TAG="$(git rev-parse --short HEAD)"
          echo "TAG=${TAG}" >> $GITHUB_ENV
  
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.saas
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository_owner }}/netmaker-ui-saas:${{ env.TAG }}

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: saas-prod-cluster-us-west

      - name: Set k8s deployment image
        run: kubectl set image deployment netmaker-ui netmaker-ui=${{ github.repository_owner }}/netmaker-ui-saas:${{ env.TAG }} -n accounts

      - name: Set Intercom vars
        run: kubectl set env deployment netmaker-ui INTERCOM_APP_ID=al371us8 -n accounts

      - name: Deploy to k8s cluster
        run: kubectl rollout restart deploy netmaker-ui -n accounts

      - name: Verify deployment
        run: kubectl rollout status deployment/netmaker-ui -n accounts
    