name: NMUI SaaS Deployment to Prod

on:
  push:
    branches:
      - saas-prod

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to saas-prod"
        uses: actions/checkout@v3
        with:
          ref: saas-prod

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.saas
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository_owner }}/netmaker-ui-saas:$(echo $GITHUB_SHA | head -c7)

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Prepare DO KUBECONFIG for prod
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 saas-prod-cluster-us-west

      - name: Deploy to DigitalOcean Kubernetes
        uses: WyriHaximus/github-action-helm3@v3
        with:
          kubeconfig: $(cat ~/.kube/config)
          exec: |
            helm upgrade -i netmaker-ui deploy/helm/netmaker-ui/ \
            --namespace accounts \
            --create-namespace \
            --set env=staging \
            --set image.accountsbackend.pullPolicy=Always \
            --set image.accountsbackend.pullPolicy=Always \
            --set image.accountsbackend.tag=$(echo $GITHUB_SHA | head -c7)
      - name: Verify deployment
        run: kubectl rollout status deployment/netmaker-ui -n accounts
